# MINI PROJECT
# SecureCheck: A Python-SQL Digital Ledger for Police Post Logs

In [11]:
### Using Python(inserting values using pandas),SQL,Streamlit

STEP:1
# Reading the excel file using Pandas&loading the data :

In [12]:
import pandas as pd

path=r"D:\Data science\Code\Mini project\traffic_stops.csv"
df=pd.read_csv(path)
df

C:\Users\GOKULA KRISHNAN.V\AppData\Local\Temp\ipykernel_21388\2096125385.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(path)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

In [13]:
df['stop_date'] = pd.to_datetime(df['stop_date'], errors='coerce').dt.date
df['stop_time'] = pd.to_datetime(df['stop_time'], errors='coerce').dt.time

C:\Users\GOKULA KRISHNAN.V\AppData\Local\Temp\ipykernel_21388\2540543617.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['stop_time'] = pd.to_datetime(df['stop_time'], errors='coerce').dt.time

# clearing null values:

In [14]:
import pandas as pd

path=r"D:\Data science\Code\Mini project\traffic_stops.csv"
df=pd.read_csv(path)

df.isna().sum()
df=df.dropna()  
df.dropna(inplace=True)
df

C:\Users\GOKULA KRISHNAN.V\AppData\Local\Temp\ipykernel_21388\374121704.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(path)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65531,2020-02-15,12:11:00,India,M,47,70,Hispanic,Seatbelt,Signal,False,Vehicle Search,Ticket,True,16-30 Min,True,WB25SO5088
65532,2020-02-15,12:12:00,India,M,50,62,White,Other,Seatbelt,True,Frisk,Arrest,True,30+ Min,True,KA83LM2787
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328

In [ ]:
#checking the null value:

df.isna().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

# Connection to Mysql connector & database :

In [16]:
import mysql.connector
connection=mysql.connector.connect(
    host='localhost',
    user='root',
    password='Disneyworld@33',
    database='Secure_Check'
)
cursor=connection.cursor()

In [ ]:
create_db="create database Secure_Check"
cursor.execute(create_db)

# Creating columns in SQL database:

In [ ]:
cursor.execute("USE Secure_Check;")

query = """
CREATE TABLE traffic_logs (
    Stop_date DATE,
    Stop_time TIME,
    Country_name VARCHAR(30),
    Driver_gender VARCHAR(10),
    Driver_age_raw INT,	
    Driver_age INT,
    Driver_race VARCHAR(30),
    Violation_raw VARCHAR(30),
    Violation VARCHAR(30),
    Search_type VARCHAR(20),
    Search_conducted VARCHAR(30),
    Stop_outcome VARCHAR(30),
    Is_arrested VARCHAR(20),
    Stop_duration VARCHAR(30),
    Drugs_related_stop VARCHAR(30),
    Vehicle_number VARCHAR(10)
);

"""

cursor.execute(query)
connection.commit()

# Inserting the dataframes into the database:

In [ ]:
import mysql.connector
connection=mysql.connector.connect(
    host='localhost',
    user='root',
    password='Disneyworld@33',
    database='secure_Check'
)
cursor=connection.cursor()


insert_dataFrame = """
INSERT INTO traffic_logs (
    Stop_date, Stop_time, Country_name, Driver_gender,
    Driver_age_raw, Driver_age, Driver_race,
    Violation_raw, Violation, Search_type,
    Search_conducted, Stop_outcome, Is_arrested,
    Stop_duration, Drugs_related_stop, Vehicle_number
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

data = [tuple(row) for row in df.itertuples(index=False)]

cursor.executemany(insert_dataFrame, data)
connection.commit()